#!/bin/bash
net="10.7.180."
oldstate="old.txt"
newstate="new.txt"
[ -s $oldstate ] || for (( i=0; i<255; i++ )); do echo 2; done >> $oldstate
state=( $(cat $oldstate) )
for i in {100..105}
do
ip="$net$i"
ping -c1 $ip &>>/dev/null
res=$?
if [ $res -ne ${state[$i]} ]
then
echo "$ip $res"
state[$i]=$res
fi
done > $newstate
echo ${state[@]} > $oldstate 
