#!/bin/bash
net="10.7.180."
oldstate="old.txt"
difstate=""
[ -s $oldstate ] || for (( i=0; i<255; i++ )); do echo 2; done >> $oldstate
state=( $(cat $oldstate) )
for i in {105..110}
do
ip="$net$i"
ping -c1 $ip &>>/dev/null
res=$?
if [ $res -ne ${state[$i]} ]
then
difstate="$difstate $ip $res"
state[$i]=$res
fi
done

[ "$difstate" ] && echo "$difstate" | mutt -s "IP configuration" yaroslav.yakymchuk27@gmail.com
echo ${state[@]} > $oldstate 
